'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
'
Namespace ExchangeRate
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ExchangeRate", [Namespace]:="urn:crmondemand/ws/ecbs/exchangerate/")>  _
    Partial Public Class ExchangeRate
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ExchangeRateInsertOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ExchangeRateQueryPageOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ExchangeRateUpdateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ExchangeRateDeleteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ExchangeRateExecuteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Update_ExchangeRate.My.MySettings.Default.Update_PartNo_ExchangeRate_ExchangeRate
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ExchangeRateInsertCompleted As ExchangeRateInsertCompletedEventHandler
        
        '''<remarks/>
        Public Event ExchangeRateQueryPageCompleted As ExchangeRateQueryPageCompletedEventHandler
        
        '''<remarks/>
        Public Event ExchangeRateUpdateCompleted As ExchangeRateUpdateCompletedEventHandler
        
        '''<remarks/>
        Public Event ExchangeRateDeleteCompleted As ExchangeRateDeleteCompletedEventHandler
        
        '''<remarks/>
        Public Event ExchangeRateExecuteCompleted As ExchangeRateExecuteCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("document/urn:crmondemand/ws/ecbs/exchangerate/:ExchangeRateInsert", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function ExchangeRateInsert(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:crmondemand/ws/ecbs/exchangerate/")> ByVal ExchangeRateInsert_Input As ExchangeRateInsert_Input) As <System.Xml.Serialization.XmlElementAttribute("ExchangeRateInsert_Output", [Namespace]:="urn:crmondemand/ws/ecbs/exchangerate/")> ExchangeRateInsert_Output
            Dim results() As Object = Me.Invoke("ExchangeRateInsert", New Object() {ExchangeRateInsert_Input})
            Return CType(results(0),ExchangeRateInsert_Output)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ExchangeRateInsertAsync(ByVal ExchangeRateInsert_Input As ExchangeRateInsert_Input)
            Me.ExchangeRateInsertAsync(ExchangeRateInsert_Input, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ExchangeRateInsertAsync(ByVal ExchangeRateInsert_Input As ExchangeRateInsert_Input, ByVal userState As Object)
            If (Me.ExchangeRateInsertOperationCompleted Is Nothing) Then
                Me.ExchangeRateInsertOperationCompleted = AddressOf Me.OnExchangeRateInsertOperationCompleted
            End If
            Me.InvokeAsync("ExchangeRateInsert", New Object() {ExchangeRateInsert_Input}, Me.ExchangeRateInsertOperationCompleted, userState)
        End Sub
        
        Private Sub OnExchangeRateInsertOperationCompleted(ByVal arg As Object)
            If (Not (Me.ExchangeRateInsertCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ExchangeRateInsertCompleted(Me, New ExchangeRateInsertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("document/urn:crmondemand/ws/ecbs/exchangerate/:ExchangeRateQueryPage", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function ExchangeRateQueryPage(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:crmondemand/ws/ecbs/exchangerate/")> ByVal ExchangeRateQueryPage_Input As ExchangeRateQueryPage_Input) As <System.Xml.Serialization.XmlElementAttribute("ExchangeRateQueryPage_Output", [Namespace]:="urn:crmondemand/ws/ecbs/exchangerate/")> ExchangeRateQueryPage_Output
            Dim results() As Object = Me.Invoke("ExchangeRateQueryPage", New Object() {ExchangeRateQueryPage_Input})
            Return CType(results(0),ExchangeRateQueryPage_Output)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ExchangeRateQueryPageAsync(ByVal ExchangeRateQueryPage_Input As ExchangeRateQueryPage_Input)
            Me.ExchangeRateQueryPageAsync(ExchangeRateQueryPage_Input, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ExchangeRateQueryPageAsync(ByVal ExchangeRateQueryPage_Input As ExchangeRateQueryPage_Input, ByVal userState As Object)
            If (Me.ExchangeRateQueryPageOperationCompleted Is Nothing) Then
                Me.ExchangeRateQueryPageOperationCompleted = AddressOf Me.OnExchangeRateQueryPageOperationCompleted
            End If
            Me.InvokeAsync("ExchangeRateQueryPage", New Object() {ExchangeRateQueryPage_Input}, Me.ExchangeRateQueryPageOperationCompleted, userState)
        End Sub
        
        Private Sub OnExchangeRateQueryPageOperationCompleted(ByVal arg As Object)
            If (Not (Me.ExchangeRateQueryPageCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ExchangeRateQueryPageCompleted(Me, New ExchangeRateQueryPageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("document/urn:crmondemand/ws/ecbs/exchangerate/:ExchangeRateUpdate", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function ExchangeRateUpdate(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:crmondemand/ws/ecbs/exchangerate/")> ByVal ExchangeRateUpdate_Input As ExchangeRateUpdate_Input) As <System.Xml.Serialization.XmlElementAttribute("ExchangeRateUpdate_Output", [Namespace]:="urn:crmondemand/ws/ecbs/exchangerate/")> ExchangeRateUpdate_Output
            Dim results() As Object = Me.Invoke("ExchangeRateUpdate", New Object() {ExchangeRateUpdate_Input})
            Return CType(results(0),ExchangeRateUpdate_Output)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ExchangeRateUpdateAsync(ByVal ExchangeRateUpdate_Input As ExchangeRateUpdate_Input)
            Me.ExchangeRateUpdateAsync(ExchangeRateUpdate_Input, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ExchangeRateUpdateAsync(ByVal ExchangeRateUpdate_Input As ExchangeRateUpdate_Input, ByVal userState As Object)
            If (Me.ExchangeRateUpdateOperationCompleted Is Nothing) Then
                Me.ExchangeRateUpdateOperationCompleted = AddressOf Me.OnExchangeRateUpdateOperationCompleted
            End If
            Me.InvokeAsync("ExchangeRateUpdate", New Object() {ExchangeRateUpdate_Input}, Me.ExchangeRateUpdateOperationCompleted, userState)
        End Sub
        
        Private Sub OnExchangeRateUpdateOperationCompleted(ByVal arg As Object)
            If (Not (Me.ExchangeRateUpdateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ExchangeRateUpdateCompleted(Me, New ExchangeRateUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("document/urn:crmondemand/ws/ecbs/exchangerate/:ExchangeRateDelete", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function ExchangeRateDelete(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:crmondemand/ws/ecbs/exchangerate/")> ByVal ExchangeRateDelete_Input As ExchangeRateDelete_Input) As <System.Xml.Serialization.XmlElementAttribute("ExchangeRateDelete_Output", [Namespace]:="urn:crmondemand/ws/ecbs/exchangerate/")> ExchangeRateDelete_Output
            Dim results() As Object = Me.Invoke("ExchangeRateDelete", New Object() {ExchangeRateDelete_Input})
            Return CType(results(0),ExchangeRateDelete_Output)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ExchangeRateDeleteAsync(ByVal ExchangeRateDelete_Input As ExchangeRateDelete_Input)
            Me.ExchangeRateDeleteAsync(ExchangeRateDelete_Input, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ExchangeRateDeleteAsync(ByVal ExchangeRateDelete_Input As ExchangeRateDelete_Input, ByVal userState As Object)
            If (Me.ExchangeRateDeleteOperationCompleted Is Nothing) Then
                Me.ExchangeRateDeleteOperationCompleted = AddressOf Me.OnExchangeRateDeleteOperationCompleted
            End If
            Me.InvokeAsync("ExchangeRateDelete", New Object() {ExchangeRateDelete_Input}, Me.ExchangeRateDeleteOperationCompleted, userState)
        End Sub
        
        Private Sub OnExchangeRateDeleteOperationCompleted(ByVal arg As Object)
            If (Not (Me.ExchangeRateDeleteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ExchangeRateDeleteCompleted(Me, New ExchangeRateDeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("document/urn:crmondemand/ws/ecbs/exchangerate/:ExchangeRateExecute", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function ExchangeRateExecute(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:crmondemand/ws/ecbs/exchangerate/")> ByVal ExchangeRateExecute_Input As ExchangeRateExecute_Input) As <System.Xml.Serialization.XmlElementAttribute("ExchangeRateExecute_Output", [Namespace]:="urn:crmondemand/ws/ecbs/exchangerate/")> ExchangeRateExecute_Output
            Dim results() As Object = Me.Invoke("ExchangeRateExecute", New Object() {ExchangeRateExecute_Input})
            Return CType(results(0),ExchangeRateExecute_Output)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ExchangeRateExecuteAsync(ByVal ExchangeRateExecute_Input As ExchangeRateExecute_Input)
            Me.ExchangeRateExecuteAsync(ExchangeRateExecute_Input, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ExchangeRateExecuteAsync(ByVal ExchangeRateExecute_Input As ExchangeRateExecute_Input, ByVal userState As Object)
            If (Me.ExchangeRateExecuteOperationCompleted Is Nothing) Then
                Me.ExchangeRateExecuteOperationCompleted = AddressOf Me.OnExchangeRateExecuteOperationCompleted
            End If
            Me.InvokeAsync("ExchangeRateExecute", New Object() {ExchangeRateExecute_Input}, Me.ExchangeRateExecuteOperationCompleted, userState)
        End Sub
        
        Private Sub OnExchangeRateExecuteOperationCompleted(ByVal arg As Object)
            If (Not (Me.ExchangeRateExecuteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ExchangeRateExecuteCompleted(Me, New ExchangeRateExecuteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:crmondemand/ws/ecbs/exchangerate/")>  _
    Partial Public Class ExchangeRateInsert_Input
        
        Private listOfExchangeRateField As ListOfExchangeRateData
        
        Private lOVLanguageModeField As String
        
        Private viewModeField As String
        
        Private echoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:/crmondemand/xml/ExchangeRate/Data")>  _
        Public Property ListOfExchangeRate() As ListOfExchangeRateData
            Get
                Return Me.listOfExchangeRateField
            End Get
            Set
                Me.listOfExchangeRateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LOVLanguageMode() As String
            Get
                Return Me.lOVLanguageModeField
            End Get
            Set
                Me.lOVLanguageModeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ViewMode() As String
            Get
                Return Me.viewModeField
            End Get
            Set
                Me.viewModeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Echo() As String
            Get
                Return Me.echoField
            End Get
            Set
                Me.echoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:/crmondemand/xml/ExchangeRate/Data")>  _
    Partial Public Class ListOfExchangeRateData
        
        Private exchangeRateField() As ExchangeRateData
        
        Private lastpageField As Boolean
        
        Private lastpageFieldSpecified As Boolean
        
        Private recordcountField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ExchangeRate")>  _
        Public Property ExchangeRate() As ExchangeRateData()
            Get
                Return Me.exchangeRateField
            End Get
            Set
                Me.exchangeRateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property lastpage() As Boolean
            Get
                Return Me.lastpageField
            End Get
            Set
                Me.lastpageField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property lastpageSpecified() As Boolean
            Get
                Return Me.lastpageFieldSpecified
            End Get
            Set
                Me.lastpageFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="integer")>  _
        Public Property recordcount() As String
            Get
                Return Me.recordcountField
            End Get
            Set
                Me.recordcountField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:/crmondemand/xml/ExchangeRate/Data")>  _
    Partial Public Class ExchangeRateData
        
        Private modifiedDateField As Date
        
        Private modifiedDateFieldSpecified As Boolean
        
        Private createdDateField As Date
        
        Private createdDateFieldSpecified As Boolean
        
        Private modifiedByIdField As String
        
        Private createdByIdField As String
        
        Private modIdField As Integer
        
        Private modIdFieldSpecified As Boolean
        
        Private idField As String
        
        Private exchangeDateField As Date
        
        Private exchangeDateFieldSpecified As Boolean
        
        Private exchangeRateField As Decimal
        
        Private exchangeRateFieldSpecified As Boolean
        
        Private fromCurrencyCodeField As String
        
        Private toCurrencyCodeField As String
        
        Private updatedByFirstNameField As String
        
        Private updatedByLastNameField As String
        
        Private updatedByUserSignInIdField As String
        
        Private updatedByAliasField As String
        
        Private updatedByFullNameField As String
        
        Private updatedByIntegrationIdField As String
        
        Private updatedByExternalSystemIdField As String
        
        Private updatedByEMailAddrField As String
        
        Private createdByFirstNameField As String
        
        Private createdByLastNameField As String
        
        Private createdByUserSignInIdField As String
        
        Private createdByAliasField As String
        
        Private createdByFullNameField As String
        
        Private createdByIntegrationIdField As String
        
        Private createdByExternalSystemIdField As String
        
        Private createdByEMailAddrField As String
        
        Private createdByField As String
        
        Private modifiedByField As String
        
        Private operationField As String
        
        '''<remarks/>
        Public Property ModifiedDate() As Date
            Get
                Return Me.modifiedDateField
            End Get
            Set
                Me.modifiedDateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ModifiedDateSpecified() As Boolean
            Get
                Return Me.modifiedDateFieldSpecified
            End Get
            Set
                Me.modifiedDateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CreatedDate() As Date
            Get
                Return Me.createdDateField
            End Get
            Set
                Me.createdDateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property CreatedDateSpecified() As Boolean
            Get
                Return Me.createdDateFieldSpecified
            End Get
            Set
                Me.createdDateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ModifiedById() As String
            Get
                Return Me.modifiedByIdField
            End Get
            Set
                Me.modifiedByIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CreatedById() As String
            Get
                Return Me.createdByIdField
            End Get
            Set
                Me.createdByIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ModId() As Integer
            Get
                Return Me.modIdField
            End Get
            Set
                Me.modIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ModIdSpecified() As Boolean
            Get
                Return Me.modIdFieldSpecified
            End Get
            Set
                Me.modIdFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property ExchangeDate() As Date
            Get
                Return Me.exchangeDateField
            End Get
            Set
                Me.exchangeDateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ExchangeDateSpecified() As Boolean
            Get
                Return Me.exchangeDateFieldSpecified
            End Get
            Set
                Me.exchangeDateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ExchangeRate() As Decimal
            Get
                Return Me.exchangeRateField
            End Get
            Set
                Me.exchangeRateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ExchangeRateSpecified() As Boolean
            Get
                Return Me.exchangeRateFieldSpecified
            End Get
            Set
                Me.exchangeRateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FromCurrencyCode() As String
            Get
                Return Me.fromCurrencyCodeField
            End Get
            Set
                Me.fromCurrencyCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ToCurrencyCode() As String
            Get
                Return Me.toCurrencyCodeField
            End Get
            Set
                Me.toCurrencyCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UpdatedByFirstName() As String
            Get
                Return Me.updatedByFirstNameField
            End Get
            Set
                Me.updatedByFirstNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UpdatedByLastName() As String
            Get
                Return Me.updatedByLastNameField
            End Get
            Set
                Me.updatedByLastNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UpdatedByUserSignInId() As String
            Get
                Return Me.updatedByUserSignInIdField
            End Get
            Set
                Me.updatedByUserSignInIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UpdatedByAlias() As String
            Get
                Return Me.updatedByAliasField
            End Get
            Set
                Me.updatedByAliasField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UpdatedByFullName() As String
            Get
                Return Me.updatedByFullNameField
            End Get
            Set
                Me.updatedByFullNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UpdatedByIntegrationId() As String
            Get
                Return Me.updatedByIntegrationIdField
            End Get
            Set
                Me.updatedByIntegrationIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UpdatedByExternalSystemId() As String
            Get
                Return Me.updatedByExternalSystemIdField
            End Get
            Set
                Me.updatedByExternalSystemIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UpdatedByEMailAddr() As String
            Get
                Return Me.updatedByEMailAddrField
            End Get
            Set
                Me.updatedByEMailAddrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CreatedByFirstName() As String
            Get
                Return Me.createdByFirstNameField
            End Get
            Set
                Me.createdByFirstNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CreatedByLastName() As String
            Get
                Return Me.createdByLastNameField
            End Get
            Set
                Me.createdByLastNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CreatedByUserSignInId() As String
            Get
                Return Me.createdByUserSignInIdField
            End Get
            Set
                Me.createdByUserSignInIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CreatedByAlias() As String
            Get
                Return Me.createdByAliasField
            End Get
            Set
                Me.createdByAliasField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CreatedByFullName() As String
            Get
                Return Me.createdByFullNameField
            End Get
            Set
                Me.createdByFullNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CreatedByIntegrationId() As String
            Get
                Return Me.createdByIntegrationIdField
            End Get
            Set
                Me.createdByIntegrationIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CreatedByExternalSystemId() As String
            Get
                Return Me.createdByExternalSystemIdField
            End Get
            Set
                Me.createdByExternalSystemIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CreatedByEMailAddr() As String
            Get
                Return Me.createdByEMailAddrField
            End Get
            Set
                Me.createdByEMailAddrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CreatedBy() As String
            Get
                Return Me.createdByField
            End Get
            Set
                Me.createdByField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ModifiedBy() As String
            Get
                Return Me.modifiedByField
            End Get
            Set
                Me.modifiedByField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property operation() As String
            Get
                Return Me.operationField
            End Get
            Set
                Me.operationField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:/crmondemand/xml/ExchangeRate/Query")>  _
    Partial Public Class queryType
        
        Private sortorderField As String
        
        Private sortsequenceField As String
        
        Private valueField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property sortorder() As String
            Get
                Return Me.sortorderField
            End Get
            Set
                Me.sortorderField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property sortsequence() As String
            Get
                Return Me.sortsequenceField
            End Get
            Set
                Me.sortsequenceField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:/crmondemand/xml/ExchangeRate/Query")>  _
    Partial Public Class ExchangeRateQuery
        
        Private modifiedDateField As queryType
        
        Private createdDateField As queryType
        
        Private modifiedByIdField As queryType
        
        Private createdByIdField As queryType
        
        Private modIdField As queryType
        
        Private idField As queryType
        
        Private exchangeDateField As queryType
        
        Private exchangeRateField As queryType
        
        Private fromCurrencyCodeField As queryType
        
        Private toCurrencyCodeField As queryType
        
        Private updatedByFirstNameField As queryType
        
        Private updatedByLastNameField As queryType
        
        Private updatedByUserSignInIdField As queryType
        
        Private updatedByAliasField As queryType
        
        Private updatedByFullNameField As queryType
        
        Private updatedByIntegrationIdField As queryType
        
        Private updatedByExternalSystemIdField As queryType
        
        Private updatedByEMailAddrField As queryType
        
        Private createdByFirstNameField As queryType
        
        Private createdByLastNameField As queryType
        
        Private createdByUserSignInIdField As queryType
        
        Private createdByAliasField As queryType
        
        Private createdByFullNameField As queryType
        
        Private createdByIntegrationIdField As queryType
        
        Private createdByExternalSystemIdField As queryType
        
        Private createdByEMailAddrField As queryType
        
        Private createdByField As queryType
        
        Private modifiedByField As queryType
        
        Private searchspecField As String
        
        '''<remarks/>
        Public Property ModifiedDate() As queryType
            Get
                Return Me.modifiedDateField
            End Get
            Set
                Me.modifiedDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CreatedDate() As queryType
            Get
                Return Me.createdDateField
            End Get
            Set
                Me.createdDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ModifiedById() As queryType
            Get
                Return Me.modifiedByIdField
            End Get
            Set
                Me.modifiedByIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CreatedById() As queryType
            Get
                Return Me.createdByIdField
            End Get
            Set
                Me.createdByIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ModId() As queryType
            Get
                Return Me.modIdField
            End Get
            Set
                Me.modIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Id() As queryType
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ExchangeDate() As queryType
            Get
                Return Me.exchangeDateField
            End Get
            Set
                Me.exchangeDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ExchangeRate() As queryType
            Get
                Return Me.exchangeRateField
            End Get
            Set
                Me.exchangeRateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FromCurrencyCode() As queryType
            Get
                Return Me.fromCurrencyCodeField
            End Get
            Set
                Me.fromCurrencyCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ToCurrencyCode() As queryType
            Get
                Return Me.toCurrencyCodeField
            End Get
            Set
                Me.toCurrencyCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UpdatedByFirstName() As queryType
            Get
                Return Me.updatedByFirstNameField
            End Get
            Set
                Me.updatedByFirstNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UpdatedByLastName() As queryType
            Get
                Return Me.updatedByLastNameField
            End Get
            Set
                Me.updatedByLastNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UpdatedByUserSignInId() As queryType
            Get
                Return Me.updatedByUserSignInIdField
            End Get
            Set
                Me.updatedByUserSignInIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UpdatedByAlias() As queryType
            Get
                Return Me.updatedByAliasField
            End Get
            Set
                Me.updatedByAliasField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UpdatedByFullName() As queryType
            Get
                Return Me.updatedByFullNameField
            End Get
            Set
                Me.updatedByFullNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UpdatedByIntegrationId() As queryType
            Get
                Return Me.updatedByIntegrationIdField
            End Get
            Set
                Me.updatedByIntegrationIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UpdatedByExternalSystemId() As queryType
            Get
                Return Me.updatedByExternalSystemIdField
            End Get
            Set
                Me.updatedByExternalSystemIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UpdatedByEMailAddr() As queryType
            Get
                Return Me.updatedByEMailAddrField
            End Get
            Set
                Me.updatedByEMailAddrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CreatedByFirstName() As queryType
            Get
                Return Me.createdByFirstNameField
            End Get
            Set
                Me.createdByFirstNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CreatedByLastName() As queryType
            Get
                Return Me.createdByLastNameField
            End Get
            Set
                Me.createdByLastNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CreatedByUserSignInId() As queryType
            Get
                Return Me.createdByUserSignInIdField
            End Get
            Set
                Me.createdByUserSignInIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CreatedByAlias() As queryType
            Get
                Return Me.createdByAliasField
            End Get
            Set
                Me.createdByAliasField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CreatedByFullName() As queryType
            Get
                Return Me.createdByFullNameField
            End Get
            Set
                Me.createdByFullNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CreatedByIntegrationId() As queryType
            Get
                Return Me.createdByIntegrationIdField
            End Get
            Set
                Me.createdByIntegrationIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CreatedByExternalSystemId() As queryType
            Get
                Return Me.createdByExternalSystemIdField
            End Get
            Set
                Me.createdByExternalSystemIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CreatedByEMailAddr() As queryType
            Get
                Return Me.createdByEMailAddrField
            End Get
            Set
                Me.createdByEMailAddrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CreatedBy() As queryType
            Get
                Return Me.createdByField
            End Get
            Set
                Me.createdByField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ModifiedBy() As queryType
            Get
                Return Me.modifiedByField
            End Get
            Set
                Me.modifiedByField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property searchspec() As String
            Get
                Return Me.searchspecField
            End Get
            Set
                Me.searchspecField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:/crmondemand/xml/ExchangeRate/Query")>  _
    Partial Public Class ListOfExchangeRateQuery
        
        Private exchangeRateField As ExchangeRateQuery
        
        Private pagesizeField As String
        
        Private startrownumField As String
        
        Private recordcountneededField As Boolean
        
        Private recordcountneededFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property ExchangeRate() As ExchangeRateQuery
            Get
                Return Me.exchangeRateField
            End Get
            Set
                Me.exchangeRateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="integer")>  _
        Public Property pagesize() As String
            Get
                Return Me.pagesizeField
            End Get
            Set
                Me.pagesizeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="integer")>  _
        Public Property startrownum() As String
            Get
                Return Me.startrownumField
            End Get
            Set
                Me.startrownumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property recordcountneeded() As Boolean
            Get
                Return Me.recordcountneededField
            End Get
            Set
                Me.recordcountneededField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property recordcountneededSpecified() As Boolean
            Get
                Return Me.recordcountneededFieldSpecified
            End Get
            Set
                Me.recordcountneededFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:crmondemand/ws/ecbs/exchangerate/")>  _
    Partial Public Class ExchangeRateInsert_Output
        
        Private listOfExchangeRateField As ListOfExchangeRateData
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:/crmondemand/xml/ExchangeRate/Data")>  _
        Public Property ListOfExchangeRate() As ListOfExchangeRateData
            Get
                Return Me.listOfExchangeRateField
            End Get
            Set
                Me.listOfExchangeRateField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:crmondemand/ws/ecbs/exchangerate/")>  _
    Partial Public Class ExchangeRateQueryPage_Input
        
        Private namedSearchSpecField As String
        
        Private listOfExchangeRateField As ListOfExchangeRateQuery
        
        Private lOVLanguageModeField As String
        
        Private viewModeField As String
        
        '''<remarks/>
        Public Property NamedSearchSpec() As String
            Get
                Return Me.namedSearchSpecField
            End Get
            Set
                Me.namedSearchSpecField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:/crmondemand/xml/ExchangeRate/Query")>  _
        Public Property ListOfExchangeRate() As ListOfExchangeRateQuery
            Get
                Return Me.listOfExchangeRateField
            End Get
            Set
                Me.listOfExchangeRateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LOVLanguageMode() As String
            Get
                Return Me.lOVLanguageModeField
            End Get
            Set
                Me.lOVLanguageModeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ViewMode() As String
            Get
                Return Me.viewModeField
            End Get
            Set
                Me.viewModeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:crmondemand/ws/ecbs/exchangerate/")>  _
    Partial Public Class ExchangeRateQueryPage_Output
        
        Private listOfExchangeRateField As ListOfExchangeRateData
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:/crmondemand/xml/ExchangeRate/Data")>  _
        Public Property ListOfExchangeRate() As ListOfExchangeRateData
            Get
                Return Me.listOfExchangeRateField
            End Get
            Set
                Me.listOfExchangeRateField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:crmondemand/ws/ecbs/exchangerate/")>  _
    Partial Public Class ExchangeRateUpdate_Input
        
        Private listOfExchangeRateField As ListOfExchangeRateData
        
        Private lOVLanguageModeField As String
        
        Private viewModeField As String
        
        Private echoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:/crmondemand/xml/ExchangeRate/Data")>  _
        Public Property ListOfExchangeRate() As ListOfExchangeRateData
            Get
                Return Me.listOfExchangeRateField
            End Get
            Set
                Me.listOfExchangeRateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LOVLanguageMode() As String
            Get
                Return Me.lOVLanguageModeField
            End Get
            Set
                Me.lOVLanguageModeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ViewMode() As String
            Get
                Return Me.viewModeField
            End Get
            Set
                Me.viewModeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Echo() As String
            Get
                Return Me.echoField
            End Get
            Set
                Me.echoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:crmondemand/ws/ecbs/exchangerate/")>  _
    Partial Public Class ExchangeRateUpdate_Output
        
        Private listOfExchangeRateField As ListOfExchangeRateData
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:/crmondemand/xml/ExchangeRate/Data")>  _
        Public Property ListOfExchangeRate() As ListOfExchangeRateData
            Get
                Return Me.listOfExchangeRateField
            End Get
            Set
                Me.listOfExchangeRateField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:crmondemand/ws/ecbs/exchangerate/")>  _
    Partial Public Class ExchangeRateDelete_Input
        
        Private listOfExchangeRateField As ListOfExchangeRateData
        
        Private lOVLanguageModeField As String
        
        Private viewModeField As String
        
        Private echoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:/crmondemand/xml/ExchangeRate/Data")>  _
        Public Property ListOfExchangeRate() As ListOfExchangeRateData
            Get
                Return Me.listOfExchangeRateField
            End Get
            Set
                Me.listOfExchangeRateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LOVLanguageMode() As String
            Get
                Return Me.lOVLanguageModeField
            End Get
            Set
                Me.lOVLanguageModeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ViewMode() As String
            Get
                Return Me.viewModeField
            End Get
            Set
                Me.viewModeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Echo() As String
            Get
                Return Me.echoField
            End Get
            Set
                Me.echoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:crmondemand/ws/ecbs/exchangerate/")>  _
    Partial Public Class ExchangeRateDelete_Output
        
        Private listOfExchangeRateField As ListOfExchangeRateData
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:/crmondemand/xml/ExchangeRate/Data")>  _
        Public Property ListOfExchangeRate() As ListOfExchangeRateData
            Get
                Return Me.listOfExchangeRateField
            End Get
            Set
                Me.listOfExchangeRateField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:crmondemand/ws/ecbs/exchangerate/")>  _
    Partial Public Class ExchangeRateExecute_Input
        
        Private listOfExchangeRateField As ListOfExchangeRateData
        
        Private lOVLanguageModeField As String
        
        Private viewModeField As String
        
        Private echoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:/crmondemand/xml/ExchangeRate/Data")>  _
        Public Property ListOfExchangeRate() As ListOfExchangeRateData
            Get
                Return Me.listOfExchangeRateField
            End Get
            Set
                Me.listOfExchangeRateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LOVLanguageMode() As String
            Get
                Return Me.lOVLanguageModeField
            End Get
            Set
                Me.lOVLanguageModeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ViewMode() As String
            Get
                Return Me.viewModeField
            End Get
            Set
                Me.viewModeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Echo() As String
            Get
                Return Me.echoField
            End Get
            Set
                Me.echoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:crmondemand/ws/ecbs/exchangerate/")>  _
    Partial Public Class ExchangeRateExecute_Output
        
        Private listOfExchangeRateField As ListOfExchangeRateData
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:/crmondemand/xml/ExchangeRate/Data")>  _
        Public Property ListOfExchangeRate() As ListOfExchangeRateData
            Get
                Return Me.listOfExchangeRateField
            End Get
            Set
                Me.listOfExchangeRateField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub ExchangeRateInsertCompletedEventHandler(ByVal sender As Object, ByVal e As ExchangeRateInsertCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ExchangeRateInsertCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ExchangeRateInsert_Output
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ExchangeRateInsert_Output)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub ExchangeRateQueryPageCompletedEventHandler(ByVal sender As Object, ByVal e As ExchangeRateQueryPageCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ExchangeRateQueryPageCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ExchangeRateQueryPage_Output
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ExchangeRateQueryPage_Output)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub ExchangeRateUpdateCompletedEventHandler(ByVal sender As Object, ByVal e As ExchangeRateUpdateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ExchangeRateUpdateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ExchangeRateUpdate_Output
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ExchangeRateUpdate_Output)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub ExchangeRateDeleteCompletedEventHandler(ByVal sender As Object, ByVal e As ExchangeRateDeleteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ExchangeRateDeleteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ExchangeRateDelete_Output
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ExchangeRateDelete_Output)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub ExchangeRateExecuteCompletedEventHandler(ByVal sender As Object, ByVal e As ExchangeRateExecuteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ExchangeRateExecuteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ExchangeRateExecute_Output
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ExchangeRateExecute_Output)
            End Get
        End Property
    End Class
End Namespace
